### ISSUE TITLE
Convert-PSToBAT cmdlet not working

### ISSUE THREAD

**Issue by ExtremePro11299** [EvilBytecode/PS2BAT#1]
I did use the newest Powershell 7 though, which might not be compatible with this module. However, since this is Powershell 7 and not Windows Powershell, the modules folder might be in a different location. I haven't tried that yet though.
![image](https://github.com/EvilBytecode/PS2BAT/assets/134209046/2baf78fc-15f0-4df8-9a90-fe88f9831cb7)

**Comment by EvilBytecode** [comment]
this is odd could you please contact me on discord? user: codepulze9
